// check login
export const CHECK_LOGIN_BEGIN = 'CHECK_LOGIN_BEGIN';
export const CHECK_LOGIN_SUCCESS = 'CHECK_LOGIN_SUCCESS';
export const CHECK_LOGIN_ERROR = 'CHECK_LOGIN_ERROR';

//user
export const USER_BEGIN = 'USER_BEGIN';
export const USER_BEGIN_SUCCESS = 'USER_BEGIN_SUCCESS';
export const USER_BEGIN_ERROR = 'USER_BEGIN_ERROR';

export const RESTORE_TOKEN = 'RESTORE_TOKEN';
export const USER_ID = 'USER_ID';
export const USER_ROLE = 'USER_ROLE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const RESTORE_LOGIN = 'RESTORE_LOGIN';

// get_type

export const GETTYPE_BEGIN = 'GETTYPE_BEGIN';
export const GETTYPE_BEGIN_SUCCESS = 'GETTYPE_BEGIN_SUCCESS';
export const GETTYPE_BEGIN_ERROR = 'GETTYPE_BEGIN_ERROR';

// get_client

export const GETCLIENT_BEGIN = 'GETCLIENT_BEGIN';
export const GETCLIENT_BEGIN_SUCCESS = 'GETCLIENT_BEGIN_SUCCESS';
export const GETCLIENT_BEGIN_ERROR = 'GETCLIENT_BEGIN_ERROR';

export const ADDCLIENT_BEGIN = 'ADDCLIENT_BEGIN';
export const ADDCLIENT_SUCCESS = 'ADDCLIENT_SUCCESS';
export const ADDCLIENT_ERROR = 'ADDCLIENT_ERROR';

export const UPDATECLIENT_BEGIN = 'UPDATECLIENT_BEGIN';
export const UPDATECLIENT_SUCCESS = 'UPDATECLIENT_SUCCESS';
export const UPDATECLIENT_ERROR = 'UPDATECLIENT_ERROR';

// get_employee

export const GETEMPLOYEE_BEGIN = 'GETEMPLOYEE_BEGIN';
export const GETEMPLOYEE_BEGIN_SUCCESS = 'GETEMPLOYEE_BEGIN_SUCCESS';
export const GETEMPLOYEE_BEGIN_ERROR = 'GETEMPLOYEE_BEGIN_ERROR';

export const ADDEMPLOYEE_BEGIN = 'ADDEMPLOYEE_BEGIN';
export const ADDEMPLOYEE_BEGIN_SUCCESS = 'ADDEMPLOYEE_BEGIN_SUCCESS';
export const ADDEMPLOYEE_BEGIN_ERROR = 'ADDEMPLOYEE_BEGIN_ERROR';

export const UPDATEEMPLOYEE_BEGIN = 'UPDATEEMPLOYEE_BEGIN';
export const UPDATEEMPLOYEE_BEGIN_SUCCESS = 'UPDATEEMPLOYEE_BEGIN_SUCCESS';
export const UPDATEEMPLOYEE_BEGIN_ERROR = 'UPDATEEMPLOYEE_BEGIN_ERROR';

// get_vendor

export const GETVENDOR_BEGIN = 'GETVENDOR_BEGIN';
export const GETVENDOR_SUCCESS = 'GETVENDOR_SUCCESS';
export const GETVENDOR_ERROR = 'GETVENDOR_ERROR';

export const ADDVENDOR_BEGIN = 'ADDVENDOR_BEGIN';
export const ADDVENDOR_SUCCESS = 'ADDVENDOR_SUCCESS';
export const ADDVENDOR_ERROR = 'ADDVENDOR_ERROR';

export const UPDATEVENDOR_BEGIN = 'UPDATEVENDOR_BEGIN';
export const UPDATEVENDOR_SUCCESS = 'UPDATEVENDOR_SUCCESS';
export const UPDATEVENDOR_ERROR = 'UPDATEVENDOR_ERROR';

// country, state ,  city

export const COUNTRY_BEGIN = 'COUNTRY_BEGIN';
export const COUNTRY_SUCCESS = 'COUNTRY_SUCCESS';
export const COUNTRY_ERROR = 'COUNTRY_ERROR';

export const STATE_BEGIN = 'STATE_BEGIN';
export const STATE_SUCCESS = 'STATE_SUCCESS';
export const STATE_ERROR = 'STATE_ERROR';

export const CITY_BEGIN = 'CITY_BEGIN';
export const CITY_SUCCESS = 'CITY_SUCCESS';
export const CITY_ERROR = 'CITY_ERROR';

// Project
export const POST_PROJECT_BEGIN = 'POST_PROJECT_BEGIN';
export const POST_PROJECT_SUCCESS = 'POST_PROJECT_SUCCESS';
export const POST_PROJECT_ERROR = 'POST_PROJECT_ERROR';
